version: '3'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    image: mysql:5.7
    volumes:
      - df-mysql:/var/lib/mysql

  example_data:
    environment:
      DATASETS: pagila
      POSTGRES_PASSWORD: root_pw
    image: aa8y/postgres-dataset
      
  redis:
    image: redis

  web:
    depends_on:
      - mysql
    environment:
      SERVERNAME: dreamfactory.local
      # HTTPS_HEADER: "on"
      # APP_KEY: YOUR_APP_KEY
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CACHE_DRIVER: redis
      CACHE_HOST: redis
      CACHE_DATABASE: 0
      CACHE_PORT: 6379

      APP_LOG_LEVEL: debug
#      LOG_TO_STDOUT: "true"
      APP_DEBUG: "true"

#      Uncomment and configure to enable emailing
#      SENDMAIL_DEFAULT_COMMAND: "/usr/sbin/sendmail -t"
#      SSMTP_root:
#      SSMTP_mailhub:
#      SSMTP_AuthUser:
#      SSMTP_AuthPass:
#      SSMTP_UseSTARTTLS:
#      SSMTP_UseTLS:
#      SSMTP_AuthMethod:
#      SSMTP_FromLineOverride:

#      Uncomment to enable Logs DB
#      LOGSDB_HOST: logsdb
#      LOGSDB_DATABASE: access_log
#      LOGSDB_USERNAME: mongoadmin
#      LOGSDB_PASSWORD: password
#      LOGSDB_ENABLED: "true"
    volumes:
      - df-storage:/opt/dreamfactory/storage
#      - ../dreamfactory-development-packages:/src/dreamfactory
    build: .
    ports:
      - "${EXTERNAL_PORT}:80"

#  Uncomment to enable Logs DB
#  logsdb:
#    image: mongo:4.0-xenial
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  df-storage:
    driver: local
  df-mysql:
    driver: local
